filebeat.inputs:
################

#sales
- type: log
  enabled: true
  paths:
      - /linuxcash/logs/current/saleUnload*.log
  fields:
    type: cash_sales
  tags: ["cash_sales"]
  fields_under_root: true
  scan_frequency: 5s

#frinit
- type: log
  enabled: true
  paths:
      - /linuxcash/logs/current/frinit.log
  fields:
    type: cash_frinit
  tags: ["cash_frinit"]
  fields_under_root: true
  scan_frequency: 5s

#frdriver
- type: log
  enabled: true
  paths:
      - /linuxcash/logs/current/frdriver.log
  fields:
    type: cash_frdriver
  tags: ["cash_frdriver"]
  fields_under_root: true
  scan_frequency: 5s

#ntpsync
- type: log
  enabled: true
  paths:
      - /linuxcash/logs/current/ntpsync.log
  fields:
    type: cash_ntpsync
  tags: ["cash_ntpsync"]
  fields_under_root: true
  scan_frequency: 5s

#terminal
- type: log
  enabled: true
  paths:
      - /linuxcash/logs/current/terminal.log
  fields:
    type: cash_terminal
  tags: ["cash_terminal"]
  fields_under_root: true
  scan_frequency: 5s

#mysql
- type: log
  enabled: true
  paths:
      - /var/log/mysql/error.log
  fields:
    type: cash_mysql_error
  tags: ["cash_mysql_error"]
  fields_under_root: true
  scan_frequency: 5s

#######################################
output.logstash:
  hosts: ["192.168.252.21:5044"]

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://192.168.252.21:9200"]
